In [ ]:
import sys
import pandas as od
import numpy as np
import sklearn
import matplotlib
import seaborn as sns

print("Library versions")
print("-" * 40)
print(f"pandas version: {od.__version__}")
print(f"numpy version: {np.__version__}")
print(f"sklearn version: {sklearn.__version__}")
print(f"matplotlib version: {matplotlib.__version__}")
print(f"seaborn version: {sns.__version__}")
print("-" * 40)

Library versions
----------------------------------------
pandas version: 2.2.2
numpy version: 2.0.2
sklearn version: 1.6.1
matplotlib version: 3.10.0
seaborn version: 0.13.2
----------------------------------------

In [ ]:
from pandas import read_csv
df=read_csv('placement_predict_50k Dataset.csv')
df.head(5)

,StudentID,Gender,City,CollegeTier,Stream,Specialisation,Hostel,HistoryOfBacklogs,SGPA_Sem1,SGPA_Sem2,...,Publications,AptitudeTestScore,SoftSkillsRating,CodingTestScore,MockInterviewScore,ExtraCurricular,CGPA_Tier,PlacementStatus,IsAnomaly,Salary Package
0,1,Male,Ahmedabad,Tier2,ECE,Networking,No,No,6.02,6.54,...,0,66.7,2.2,49.4,47.8,0,Low,0,0,0.00
1,2,Female,Mumbai,Tier2,ECE,DataScience,Yes,Yes,5.84,5.12,...,0,48.2,2.4,26.7,25.8,0,Low,0,0,0.00
2,3,Male,Kolkata,Tier2,IT,DataScience,Yes,No,4.91,5.29,...,0,73.8,2.8,67.7,41.5,0,Low,1,0,3.89
3,4,Male,Jaipur,Tier1,CS,AI,No,No,7.67,8.03,...,0,69.8,2.7,66.9,48.0,0,Mid,1,0,8.37
4,5,Male,Pune,Tier2,IT,DataScience,Yes,No,8.14,8.97,...,1,73.1,2.1,71.7,61.7,1,High,1,0,18.99

In [ ]:
from pandas import read_csv
df=read_csv('placement_predict_50k Dataset.csv')
df.tail(10)

,StudentID,Gender,City,CollegeTier,Stream,Specialisation,Hostel,HistoryOfBacklogs,SGPA_Sem1,SGPA_Sem2,...,Publications,AptitudeTestScore,SoftSkillsRating,CodingTestScore,MockInterviewScore,ExtraCurricular,CGPA_Tier,PlacementStatus,IsAnomaly,Salary Package
49990,49991,Male,Delhi,Tier2,IT,DataScience,Yes,No,7.75,7.21,...,0,66.5,3.8,56.4,61.7,1,Mid,1,0,8.92
49991,49992,Female,Chennai,Tier1,CS,Networking,No,No,7.17,7.46,...,1,72.6,1.5,57.4,58.1,0,Mid,1,0,8.49
49992,49993,Male,Ahmedabad,Tier1,CS,Embedded,No,Yes,5.89,5.88,...,1,74.5,2.9,NaN,44.7,0,Low,0,0,0.00
49993,49994,Female,Kolkata,Tier2,CS,AI,Yes,Yes,8.13,8.52,...,1,68.4,4.1,90.0,75.1,1,High,1,0,22.68
49994,49995,Female,Kolkata,Tier2,CS,DataScience,Yes,No,7.46,7.37,...,0,57.2,2.6,55.3,47.0,0,Mid,1,0,8.08
49995,49996,Male,Pune,Tier2,Mechanical,Networking,No,No,7.84,8.45,...,1,75.8,3.9,54.2,NaN,0,High,1,0,18.14
49996,49997,Male,Bangalore,Tier2,EE,AI,No,No,6.08,6.12,...,2,81.4,3.8,56.1,67.7,0,Low,1,0,3.36
49997,49998,Male,Ahmedabad,Tier1,Civil,DataScience,Yes,Yes,5.69,6.09,...,0,NaN,3.1,49.1,57.7,1,Low,0,0,0.00
49998,49999,Female,Bangalore,Tier3,CS,DataScience,No,No,6.02,6.31,...,1,74.5,2.5,NaN,48.3,1,Low,0,0,0.00
49999,50000,Female,Delhi,Tier2,ECE,Networking,No,No,6.51,6.37,...,0,58.3,2.3,29.5,30.6,0,Low,0,0,0.00

In [ ]:
df.shape

(50000, 32)

In [ ]:
rows, columns=df.shape
rows

50000

In [ ]:
df['StudentID']

0            1
1            2
2            3
3            4
4            5
         ...
49995    49996
49996    49997
49997    49998
49998    49999
49999    50000
Name: StudentID, Length: 50000, dtype: int64

In [ ]:
df.columns

Index(['StudentID', 'Gender', 'City', 'CollegeTier', 'Stream',
       'Specialisation', 'Hostel', 'HistoryOfBacklogs', 'SGPA_Sem1',
       'SGPA_Sem2', 'SGPA_Sem3', 'SGPA_Sem4', 'SGPA_Sem5', 'SGPA_Sem6',
       'SGPA_Sem7', 'SGPA_Sem8', 'CGPA', 'AttendancePercent', 'Internships',
       'Projects', 'Workshops', 'Certifications', 'Publications',
       'AptitudeTestScore', 'SoftSkillsRating', 'CodingTestScore',
       'MockInterviewScore', 'ExtraCurricular', 'CGPA_Tier', 'PlacementStatus',
       'IsAnomaly', 'Salary Package'],
      dtype='object')

In [ ]:
df.dtypes

StudentID               int64
Gender                 object
City                   object
CollegeTier            object
Stream                 object
Specialisation         object
Hostel                 object
HistoryOfBacklogs      object
SGPA_Sem1             float64
SGPA_Sem2             float64
SGPA_Sem3             float64
SGPA_Sem4             float64
SGPA_Sem5             float64
SGPA_Sem6             float64
SGPA_Sem7             float64
SGPA_Sem8             float64
CGPA                  float64
AttendancePercent     float64
Internships             int64
Projects                int64
Workshops             float64
Certifications          int64
Publications            int64
AptitudeTestScore     float64
SoftSkillsRating      float64
CodingTestScore       float64
MockInterviewScore    float64
ExtraCurricular         int64
CGPA_Tier              object
PlacementStatus         int64
IsAnomaly               int64
Salary Package        float64
dtype: object

In [ ]:
df.dtypes.value_counts()

float64    16
int64       8
object      8
Name: count, dtype: int64

In [ ]:
df = df.drop_duplicates

In [ ]:
df["PlacementStatus"].value_counts()

TypeError: 'method' object is not subscriptable